'use strict';
/* ============================================================================
 *  tools/build-exe.js — build BTC-Monitor.exe (Windows x64), a standalone
 *  executable that needs no Node.js installation (Node "single executable
 *  application"). Can be run from Linux, macOS or Windows.
 *
 *    npm run build:exe           -> BTC-Monitor.exe at the project root
 *  (runs the tool with Node 20 via npx: the Windows Node 20 binary is ~15% smaller
 *   than Node 22, which keeps the archive small; any Node >= 20.12 works)
 *
 *  Steps: bundle the server with esbuild -> generate the SEA blob (with the
 *  public/ and config.js assets embedded) -> download the official
 *  Windows node.exe of the same version from nodejs.org (SHA-256 verified)
 *  -> inject the blob with postject.
 * ========================================================================== */
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { execSync } = require('child_process');

const ROOT = path.join(__dirname, '..');
const BUILD = path.join(ROOT, 'build');
const NODE_VERSION = process.version; // the blob must be generated by the same Node version as the target binary
const OUT = path.join(ROOT, 'BTC-Monitor.exe');
fs.mkdirSync(BUILD, { recursive: true });

function run(cmd, opts) { console.log('> ' + cmd); execSync(cmd, Object.assign({ stdio: 'inherit', cwd: ROOT }, opts || {})); }
/** Remove the PE certificate table (Authenticode signature) so the patched exe is cleanly unsigned. */
function stripSignature(file) {
  const buf = fs.readFileSync(file);
  const eLfanew = buf.readUInt32LE(0x3c);
  if (buf.toString('latin1', eLfanew, eLfanew + 4) !== 'PE\0\0') return;
  const opt = eLfanew + 24;
  const magic = buf.readUInt16LE(opt);
  const dd = opt + (magic === 0x20b ? 112 : 96) + 4 * 8; // data directory #4 = security
  const secOff = buf.readUInt32LE(dd), secSize = buf.readUInt32LE(dd + 4);
  if (!secSize) return;
  const out = (secOff + secSize === buf.length) ? buf.subarray(0, secOff) : buf;
  out.writeUInt32LE(0, dd); out.writeUInt32LE(0, dd + 4);
  out.writeUInt32LE(0, opt + 64); // checksum (not verified for applications)
  fs.writeFileSync(file, out);
  console.log('signature removed');
}
function walk(dir, base, out) { for (const n of fs.readdirSync(dir)) { const f = path.join(dir, n); if (fs.statSync(f).isDirectory()) walk(f, base, out); else out.push(path.relative(base, f).replace(/\\/g, '/')); } return out; }

async function download(url, file) {
  const net = require('../server/net'); net.configure(require('../config'));
  const { getBytes } = net;
  process.stdout.write(`downloading ${url} … `);
  const { buffer } = await getBytes(url, { timeout: 600000 });
  fs.writeFileSync(file, buffer);
  console.log(`${(buffer.length / 1048576).toFixed(1)} MB`);
  return buffer;
}

(async () => {
  const major = +NODE_VERSION.slice(1).split('.')[0];
  if (major < 20) throw new Error('Node.js 20.12+ is required to build the executable (assets support)');

  // 1. bundle ---------------------------------------------------------------
  const bundle = path.join(BUILD, 'server.cjs');
  run(`npx --yes esbuild server/index.js --bundle --platform=node --format=cjs --target=node${major} --outfile="${bundle}" --external:bufferutil --external:utf-8-validate --external:https-proxy-agent --external:undici --log-level=warning`);

  // 2. SEA config with embedded assets --------------------------------------
  const assets = {};
  for (const rel of walk(path.join(ROOT, 'public'), ROOT, [])) assets[rel] = path.join(ROOT, rel);
  assets['config.js'] = path.join(ROOT, 'config.js');
  const seaCfg = { main: bundle, output: path.join(BUILD, 'sea-prep.blob'), disableExperimentalSEAWarning: true, useCodeCache: false, assets };
  fs.writeFileSync(path.join(BUILD, 'sea-config.json'), JSON.stringify(seaCfg, null, 2));
  run(`"${process.execPath}" --experimental-sea-config "${path.join(BUILD, 'sea-config.json')}"`);

  // 3. official Windows binary ---------------------------------------------
  const nodeExe = path.join(BUILD, `node-${NODE_VERSION}-win-x64.exe`);
  if (!fs.existsSync(nodeExe)) {
    const base = `https://nodejs.org/dist/${NODE_VERSION}/`;
    const sums = (await download(base + 'SHASUMS256.txt', path.join(BUILD, 'SHASUMS256.txt'))).toString();
    const line = sums.split('\n').find(l => l.trim().endsWith('win-x64/node.exe'));
    if (!line) throw new Error('win-x64/node.exe not found in SHASUMS256.txt for ' + NODE_VERSION);
    const expected = line.trim().split(/\s+/)[0];
    const buf = await download(base + 'win-x64/node.exe', nodeExe);
    const actual = crypto.createHash('sha256').update(buf).digest('hex');
    if (actual !== expected) { fs.unlinkSync(nodeExe); throw new Error('SHA-256 mismatch for node.exe'); }
    console.log('node.exe SHA-256 verified');
  }

  // 4. strip Microsoft's Authenticode signature (it would be invalid after injection) and inject
  fs.copyFileSync(nodeExe, OUT);
  stripSignature(OUT);
  run(`npx --yes postject "${OUT}" NODE_SEA_BLOB "${seaCfg.output}" --sentinel-fuse NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2`);
  console.log(`\nbuilt ${OUT} (${(fs.statSync(OUT).size / 1048576).toFixed(1)} MB)`);
})().catch((e) => { console.error('build failed: ' + (e.stack || e)); process.exit(1); });
